export const ENDPOINTS = {
  admin: {
    dashboard: '/api/admin/dashboard',
    users: {
      index: '/api/admin/users',
      store: '/api/admin/users',
      byId: (id: number) => `/api/admin/users/${id}`,
      activate: (id: number) => `/api/admin/users/${id}/activate`,
      deactivate: (id: number) => `/api/admin/users/${id}/deactivate`,
      suspend: (id: number) => `/api/admin/users/${id}/ban`,
      unsuspend: (id: number) => `/api/admin/users/${id}/unsuspend`,
      resetPassword: (id: number) => `/api/admin/users/${id}/reset-password`,
      resetMfa: (id: number) => `/api/admin/users/${id}/mfa-reset`,
      bulkAction: '/api/admin/users/bulk',
      assignRole: (id: number) => `/api/admin/users/${id}/assign-role`,
      impersonate: (id: number) => `/api/admin/users/${id}/impersonate`,
      unlock: (id: number) => `/api/admin/users/${id}/unlock`,
      sessions: (id: number) => `/api/admin/users/${id}/sessions`,
      ban: (id: number) => `/api/admin/users/${id}/ban`,
      unban: (id: number) => `/api/admin/users/${id}/unsuspend`,
      dataExports: (id: number) => `/api/admin/users/${id}/data-exports`,
      requestDataExport: (id: number) => `/api/admin/users/${id}/data-exports`,
    },
    appeals: {
      index: '/api/admin/appeals',
      resolve: (id: number) => `/api/admin/appeals/${id}/resolve`,
    },
    scim: {
      tokens: {
        index: '/api/admin/scim/tokens',
        store: '/api/admin/scim/tokens',
        destroy: (id: string | number) => `/api/admin/scim/tokens/${id}`,
      },
      config: '/api/admin/scim/config',
    },
    clients: {
      index: '/api/admin/clients',
      store: '/api/admin/clients',
      byId: (id: string) => `/api/admin/clients/${id}`,
      update: (id: string) => `/api/admin/clients/${id}`,
      destroy: (id: string) => `/api/admin/clients/${id}`,
      rotateSecret: (id: string) => `/api/admin/clients/${id}/rotate-secret`,
      branding: (id: string) => `/api/admin/clients/${id}/branding`,
    },
    saml: {
      config: '/api/admin/saml/config',
      metadata: '/api/admin/saml/metadata',
      uploadMetadata: '/api/admin/saml/metadata/upload',
      fetchRemoteMetadata: '/api/admin/saml/metadata/remote',
      recentEntities: '/api/admin/saml/entities/recent',
    },
    ssf: {
      config: '/api/admin/ssf/config',
      updateConfig: '/api/admin/ssf/config',
      test: '/api/admin/ssf/test',
      broadcast: '/api/admin/ssf/broadcast',
    },
    jwks: {
      index: '/api/admin/jwks',
      show: (kid: string) => `/api/admin/jwks/${kid}`,
      store: '/api/admin/jwks',
      rotate: '/api/admin/jwks/rotate',
      destroy: (kid: string) => `/api/admin/jwks/${kid}`,
    },
    scopes: {
      list: '/api/admin/scopes',
      store: '/api/admin/scopes',
      byId: (id: number) => `/api/admin/scopes/${id}`,
      update: (id: number) => `/api/admin/scopes/${id}`,
      destroy: (id: number) => `/api/admin/scopes/${id}`,
    },
    domains: {
      verify: '/api/admin/domains/verify',
      check: '/api/admin/domains/check',
    },
    webhooks: {
      index: '/api/admin/webhooks',
      store: '/api/admin/webhooks',
      byId: (id: number) => `/api/admin/webhooks/${id}`,
      update: (id: number) => `/api/admin/webhooks/${id}`,
      destroy: (id: number) => `/api/admin/webhooks/${id}`,
      test: (id: number) => `/api/admin/webhooks/${id}/test`,
    },
    organizations: {
      index: '/api/admin/organizations',
      store: '/api/admin/organizations',
      byId: (id: number) => `/api/admin/organizations/${id}`,
      destroy: (id: number) => `/api/admin/organizations/${id}`,
      addMember: (id: number) => `/api/admin/organizations/${id}/members`,
      removeMember: (id: number, userId: number) =>
        `/api/admin/organizations/${id}/members/${userId}`,
      logo: (id: number) => `/api/admin/organizations/${id}/logo`,
      invite: (id: number) => `/api/admin/organizations/${id}/invite`,
      invitations: (id: number) => `/api/admin/organizations/${id}/invitations`,
      revokeInvitation: (orgId: number, invitationId: number | string) =>
        `/api/admin/organizations/${orgId}/invitations/${invitationId}/revoke`,
      policies: (id: number) => `/api/admin/organizations/${id}/policies`,
      impersonate: (id: number) => `/api/admin/organizations/${id}/impersonate`,
    },
    provisioning: {
      index: '/api/admin/provisioning',
      store: '/api/admin/provisioning',
      connectors: '/api/admin/provisioning',
      byId: (id: number) => `/api/admin/provisioning/${id}`,
      update: (id: number) => `/api/admin/provisioning/${id}`,
      destroy: (id: number) => `/api/admin/provisioning/${id}`,
      sync: (id: number) => `/api/admin/provisioning/${id}/sync`,
      logs: (id: number) => `/api/admin/provisioning/${id}/logs`,
      syncConnector: (id: number) => `/api/admin/provisioning/${id}/sync`,
      connectorLogs: (id: number) => `/api/admin/provisioning/${id}/logs`,
    },
    auditLogs: {
      index: '/api/admin/audit-logs',
      export: '/api/audit/logs/export',
      security: '/api/admin/security-logs',
      impersonation: '/api/admin/impersonation-logs',
      statistics: '/api/audit/statistics',
    },
    email: {
      templates: '/api/admin/email/templates',
      templateById: (id: string) => `/api/admin/email/templates/${id}`,
      preview: '/api/admin/email/preview',
      test: '/api/admin/email/test',
    },
    statistics: {
      overview: '/api/admin/statistics/summary',
      users: '/api/admin/statistics/users',
      mfa: '/api/admin/statistics/mfa',
      sessionStatistics: '/api/admin/statistics/session-statistics',
      trends: '/api/admin/statistics/trends',
    },
    impersonationLogs: '/api/admin/impersonation-logs',
    security: {
      health: '/api/admin/security/health',
    },
    docs: '/api/admin/docs',
    sandboxExecute: '/api/admin/sandbox/execute',
  },
  rbac: {
    roles: {
      list: '/api/admin/rbac/roles',
      stats: '/api/admin/rbac/roles/stats',
      store: '/api/admin/rbac/roles',
      byId: (id: number) => `/api/admin/rbac/roles/${id}`,
      update: (id: number) => `/api/admin/rbac/roles/${id}`,
      destroy: (id: number) => `/api/admin/rbac/roles/${id}`,
      permissions: (role: string) => `/api/admin/rbac/roles/${role}/permissions`,
      assignPermission: '/api/admin/rbac/roles/assign-permission',
      syncPermissions: (id: number) => `/api/admin/rbac/roles/${id}/permissions`,
      syncParents: (id: number) => `/api/admin/rbac/roles/${id}/parents`,
    },
    permissions: {
      list: '/api/admin/rbac/permissions',
      byId: (id: number) => `/api/admin/rbac/permissions/${id}`,
      store: '/api/admin/rbac/permissions',
      grant: '/api/admin/rbac/permissions/grant',
      revoke: '/api/admin/rbac/permissions/revoke',
    },
    users: {
      assignRole: '/api/admin/rbac/users/assign-role',
    },
    members: {
      overrides: (id: number) => `/api/admin/rbac/members/${id}/overrides`,
      addOverride: (id: number) => `/api/admin/rbac/members/${id}/overrides`,
      removeOverride: (id: number, pid: number) => `/api/admin/rbac/members/${id}/overrides/${pid}`,
    },
    accessPolicies: '/api/admin/rbac/access-policies',
  },
} as const
