/// <reference types="vite/client" />
import './types/pwa.d.ts'
import './types/mui.d.ts'

export { default as defaultCoreTheme } from './theme'
export { zIndexScale } from './theme/zIndex'
export { default as GlobalZIndexStyles } from './theme/GlobalZIndexStyles'
export { SettingsProvider, useSettingsLegacy, type Settings } from './contexts/settingsContext'
export * from './types'
export * from './services'
export * from './i18n/i18n'
export * from './store'
export { default as themeConfig } from './configs/themeConfig'
export * from './components'

export * from './utils'
export * from './assembly'
export * from './hooks/usePermissions'
export { TenantProvider, useTenant } from './contexts/tenantContext'
export * from './contexts/tenantContext'
export * from './hooks/useDynamicTheme'
export * from './services/tenantService'
export * from './types/tenant'
export * from './hooks/useNetworkSync'
export * from './hooks/useNavigation'
