const Path = {
  signin: '/auth/sign-in',
  signinV2: '/auth/sign-in-v2',
  login: '/auth/login',
  signup: '/auth/sign-up',
  signupV2: '/auth/sign-up-v2',
  registration: '/auth/register',
  signupSuccess: '/auth/sign-up/success',
  checkEmail: '/auth/verify-email-confirmation',
  verifyEmail: '/auth/verify-email/:email',
  verificationLinkExpired: '/auth/verification-link-expired',
  forgotPassword: '/auth/recovery/forgot-password',
  resetPassword: '/auth/recovery/reset-password',
  setNewPassword: '/auth/recovery/set-new-password/:email',
  passwordResetSuccess: '/auth/recovery/password-reset-success',
  registrationSuccess: '/auth/registration-success',
  emailVerification: '/auth/verification/email-sent',
  emailVerifiedSuccess: '/auth/verify-email/success',
  requestEmailChange: '/auth/email/request-change',
  initiateEmailChange: '/auth/email/initiate-change',
  emailChangeVerificationPending: '/auth/email/change-verification-pending',
  emailChangeVerification: '/auth/email/verify-change/:token',
  emailChangeSuccess: '/auth/email/change-success',
  emailChangeFailed: '/auth/email/change-failed',
  emailChangeStatus: '/auth/email/change-status',
  passwordlessVerification: '/auth/verify-passwordless/:token',
  mfaVerification: '/auth/mfa/verification',
  exportVerification: '/auth/export/verification',

  permissionConsent: '/auth/sso/consent',
  oidcLoginPrompt: '/auth/sso/oidc-prompt',
  providerSelection: '/auth/sso/select-provider',
  authWait: '/auth/sso/wait',

  samlMetadataDisplay: '/auth/sso/saml-metadata',
  samlMetadataBrowser: '/auth/sso/saml-browser',
  oidcConfigBrowser: '/auth/sso/oidc-config',
  oidcClientCreate: '/auth/sso/oidc-config/create',
  oidcClientEdit: '/auth/sso/oidc-config/:id/edit',
  samlConfigDashboard: '/auth/sso/saml-config',
  ssfConfiguration: '/auth/sso/ssf-config',
  jwksManagement: '/auth/sso/jwks',
  
  oidcWait: '/auth/sso/oidc/wait',
  samlWait: '/auth/sso/saml/wait',
  samlSSOInitiation: '/auth/sso/login',

  emailTestingDashboard: '/monitoring/email-testing',
  emailTemplatePreview: '/monitoring/email-templates/:id',
  loginHistory: '/auth/login-history',

  unauthorized401: '/auth/system/unauthorized',
  maintenance: '/auth/system/maintenance',
  tooManyRequests429: '/auth/system/too-many-requests',
  csrfError: '/auth/system/csrf-error',
  forbidden403: '/auth/system/forbidden',
  browserNotSupported: '/auth/system/browser-not-supported',
  deviceCode: '/auth/device/code',
  adminLogin: '/auth/admin/login',

  team: '/team',
  joinOrganization: '/auth/join-organization',
}

export default Path
